linters:
  - import:
      packages: ['denspart']
  - pylint:
  - black:
  - pydocstyle:
  - whitespace:
  - header:
      extra: []
      shebang: '#!/usr/bin/env python3'
  - yamllint:
      filefilter: ['- *conda.recipe/meta.yaml', '+ *.yml', '+ *.yaml']
  - rst-lint:
      filefilter: ['+ README.rst']
