package:
  version: "{{ PROJECT_VERSION }}"
  name: 'denspart'

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps"
  entry_points:
    - denspart-from-horton3 = denspart.adapters.horton3:main
    - denspart-from-gpaw = denspart.adapters.gpaw:main
    - denspart-from-adf = denspart.adapters.adf:main
    - denspart = denspart.__main__:main
    - denspart-write-extxyz = denspart.utils.write_extxyz:main

requirements:
  host:
    - python
    - numpy >=1.0
    - setuptools
  run:
    - python
    - qc-grid
    - importlib_resources  # [py<37]

test:
  imports:
    - denspart

about:
  dev_url: https://github.com/theochem/denspart
  description: Collection of configurable development workflows
  license: GPL-3.0
  license_family: GPL
  home: https://github.com/theochem/denspart
  license_file: LICENSE.txt
  doc_url: https://github.com/theochem/denspart
